version: '3'

services:
  spark:
    image: docker.io/bitnami/spark:3.2
    # build: .
    hostname: spark
    networks:
      - default_network
    volumes:
    - ./app:/usr/local/spark/app #Spark Scripts (Must be the same path in airflow and Spark Cluster)
    - ./resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8081:8080'
  
  spark-worker:
    image: docker.io/bitnami/spark:3.2
    # build: .
    networks:
      - default_network
    volumes:
    - ./app:/usr/local/spark/app #Spark Scripts (Must be the same path in airflow and Spark Cluster)
    - ./resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

networks:
  default_network:
    name: default_network